### ISSUE TITLE
about training

### ISSUE THREAD

**Issue by UestcJay** [zhangyk18/GeoBi-GNN#1]
many thanks for your work! In the paper, a vertex updating strategy is performed, where is this strategy reflected in the code? Thanks for your time!

**Comment by zhangyk18** [comment]
[data_util.py](https://github.com/zhangyk18/GeoBi-GNN/blob/master/data_util.py#L492)
Sorry for the boring codes, please feel free to contact me if there are any problems.

**Comment by UestcJay** [comment]
Thanks for your reply! do you mean the update strategy is only used in test stage? In training, the normal can not be used for update position?

**Comment by zhangyk18** [comment]
Yes you're right, just like the other methods for mesh denoising
