### ISSUE TITLE
Could you tell me your training environment and how to use train_dual.py?

### ISSUE THREAD

**Issue by WildEchoes** [zhangyk18/GeoBi-GNN#4]
it seems to need some files(.txt)。

**Comment by zhangyk18** [comment]
Hi, sorry for the messy codes and my late reply.
I have just updated the repo.
The environment I have tested:
-   pytorch 1.11.0
-   pytorch-geometric 2.1.0
-   openmesh 1.2.1

And certainly other versions of the above libraries may also work.
