### ISSUE TITLE
Other network in network.py

### ISSUE THREAD

**Issue by lam1101999** [zhangyk18/GeoBi-GNN#5]
Hi! I see some other networks in network.py: FacetAttentionGNN, GATGNN, FGCNet,... But only DualGNN and its child GNNModule are used, can you tell me why. Is it your future work? I'm worry of missing something, thanks.

**Comment by zhangyk18** [comment]
Hello!
Actually, these modules are just for testing in the early stages of my implementation of this idea.
I found that the GNNModule used in Facet Graph Convolution has the best performance.
So you can just ignore these useless code during runtime.
(Maybe I will clear these recently

**Comment by lam1101999** [comment]
Thank you. So I don't have to worry about understanding them all =))
